import type { L10n } from "./types";

/**
 * Photo manifest. Every photo on the site is referenced by key from here.
 *
 * Real photos come from `pnpm images:import`:
 *  - k-stan.vn.ua homepage (1920×1080 exteriors),
 *  - hotels3d.com listing (400×200 previews of the rooms — the full-resolution
 *    360° panoramas are on 3d-tours.com.ua; ask the owner for originals).
 * The four sauna photos come from the business's Instagram post
 * instagram.com/p/Bb7CEptFTN3, cropped to remove Instagram's arrows and dots.
 *
 * `placeholder: true` marks an illustrated stand-in generated by
 * `pnpm images:placeholders` for shots that don't exist yet (interiors, food).
 * Replace the file in public/images/ with a real photo (same name, WebP,
 * ≥1600px wide), update width/height and set `placeholder` to false.
 */
export type SiteImage = {
  src: string;
  alt: L10n;
  width: number;
  height: number;
  placeholder: boolean;
  /** Real photo, but too small to show large (keep it to cards/thumbnails). */
  lowRes?: boolean;
};

const photo = (name: string, alt: L10n, width = 1920, height = 1080): SiteImage => ({
  src: `/images/${name}.webp`,
  alt,
  width,
  height,
  placeholder: false,
  ...(width < 1000 ? { lowRes: true } : {}),
});

const placeholder = (name: string, alt: L10n): SiteImage => ({
  src: `/images/${name}.webp`,
  alt,
  width: 1600,
  height: 1000,
  placeholder: true,
});

export const images = {
  hero: photo("hero-korchma", {
    uk: "Зрубова корчма «Козацький Стан» з балконом серед зеленого лісу",
    en: "The Kozatskyi Stan log tavern with its balcony, surrounded by green forest",
  }),
  exteriorStreet: photo("exterior-street", {
    uk: "Дерев'яні будівлі комплексу і вежа вздовж внутрішньої вулиці",
    en: "Log buildings and a tower along the complex's inner street",
  }),
  exteriorGate: photo("exterior-gate", {
    uk: "В'їзна брама з вивіскою «Корчма Козацький Стан»",
    en: "Entrance gate with the “Kozatskyi Stan tavern” sign",
  }),
  exteriorCottages: photo("exterior-cottages", {
    uk: "Ряд дерев'яних закритих будиночків з різьбленими вікнами",
    en: "A row of enclosed wooden cottages with lattice windows",
  }),
  exteriorCourtyard: photo("exterior-courtyard", {
    uk: "Бруківчане подвір'я з дерев'яними гойдалками",
    en: "Cobblestone courtyard with wooden swing benches",
  }),
  exteriorPond: photo("exterior-pond", {
    uk: "Ставок з фонтаном серед альтанок у лісі",
    en: "Pond with a fountain among the gazebos in the forest",
  }),
  exteriorKorchma: photo(
    "exterior-korchma",
    { uk: "Корчма «Козацький Стан» — головний вхід", en: "Kozatskyi Stan tavern — main entrance" },
    400,
    200,
  ),
  roomStandard: photo(
    "room-standard",
    {
      uk: "Стандартний номер з двоспальним ліжком і аркою з каменю",
      en: "Standard room with a double bed and a stone-arched window",
    },
    400,
    200,
  ),
  vipHouse22: photo(
    "vip-house",
    {
      uk: "Вітальня VIP-будинку №22 з круглою дерев'яною стелею та шкіряними кріслами",
      en: "VIP house №22 lounge with a round timber ceiling and leather armchairs",
    },
    400,
    200,
  ),
  vipHouse18: photo(
    "vip-house-18",
    {
      uk: "VIP-будинок №18: стіни з колод, шкіряні дивани і ліжко",
      en: "VIP house №18: log walls, leather sofas and a bed",
    },
    400,
    200,
  ),
  vipHouseSmall: placeholder("vip-house-small", {
    uk: "Малий дерев'яний будиночок у лісі",
    en: "Small wooden cottage in the forest",
  }),
  sauna: photo(
    "sauna-pool",
    {
      uk: "Басейн сауни в зрубі з колод, дерев'яні лавки під вікнами",
      en: "The sauna's plunge pool in a log-walled room with wooden benches",
    },
    1140,
    735,
  ),
  saunaSteamRoom: photo(
    "sauna-steam-room",
    {
      uk: "Парилка з полицями та кам'янкою біля цегляної стіни",
      en: "Steam room with wooden benches and the stone-filled stove",
    },
    1136,
    735,
  ),
  saunaPoolLadder: photo(
    "sauna-pool-ladder",
    {
      uk: "Басейн з драбинкою і дерев'яні сходи на другий поверх",
      en: "Pool with a ladder and the wooden stairs to the upper floor",
    },
    1128,
    732,
  ),
  saunaRestRoom: photo(
    "sauna-rest-room",
    {
      uk: "Кімната відпочинку під дерев'яним дахом з різьбленими лавами",
      en: "Rest room under the timber roof with carved benches and a table",
    },
    1140,
    727,
  ),
  banquetHall: photo(
    "banquet-hall",
    {
      uk: "Банкетна зала з дерев'яними балками, кованими люстрами і портретами козаків",
      en: "Banquet hall with timber beams, wrought-iron chandeliers and Cossack portraits",
    },
    1920,
    1027,
  ),
  restaurantGazebo: photo(
    "restaurant-gazebo",
    {
      uk: "Гості в альтанці під солом'яним дахом і лавка серед лісу",
      en: "Guests dining in a thatched gazebo and a bench in the forest",
    },
    1920,
    1280,
  ),
  food: placeholder("food-grill", { uk: "Страви з мангала", en: "Dishes from the charcoal grill" }),
} satisfies Record<string, SiteImage>;

export type ImageKey = keyof typeof images;

/** Large, real photos first; low-res room previews and placeholders are left out of the gallery. */
export const galleryKeys: ImageKey[] = [
  "hero",
  "exteriorGate",
  "exteriorStreet",
  "exteriorPond",
  "exteriorCottages",
  "exteriorCourtyard",
  "banquetHall",
  "restaurantGazebo",
  "sauna",
  "saunaSteamRoom",
  "saunaPoolLadder",
  "saunaRestRoom",
];

/** Photos shown on the sauna page, main photo first. */
export const saunaKeys: ImageKey[] = ["sauna", "saunaSteamRoom", "saunaPoolLadder", "saunaRestRoom"];
